name: fcrm_chat_flutter
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  fcrm_chat_sdk:
    git:
      url: https://github.com/ipchi/fcrm_chat_sdk.git
      ref: main
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  formz: ^0.8.0
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
# flutter:
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#

# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
