name: hilol_chat_flutter
description: "Hilol Chat Flutter"
version: 0.0.2
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  fcrm_chat_sdk:
    git:
      url: https://github.com/ipchi/fcrm_chat_sdk.git
      ref: main
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  formz: ^0.8.0
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  svg_flutter: ^0.0.1
  url_launcher: ^6.3.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.8.0

flutter:
  assets:
    - lib/src/assets/icons/
    - lib/src/assets/images/
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
